name: Lint files
on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: |
          npm install
      - name: Lint files
        run: |
          npm run lint
